Try and prevent key from getting split on the command line.

diff --git a/hooks/build b/hooks/build
--- a/hooks/build
+++ b/hooks/build
@@ -1,5 +1,5 @@
 #!/bin/bash
 
 echo In hooks/build!
-docker build --build-arg ID_RSA_PRIV=$ID_RSA_PRIV -f $DOCKERFILE_PATH -t $IMAGE_NAME .
+docker build --build-arg "ID_RSA_PRIV=$ID_RSA_PRIV" -f $DOCKERFILE_PATH -t $IMAGE_NAME . || exit 1 # make failure here fail the job
 echo Done with hooks/build!
